# Generated by Django 3.0.8 on 2020-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
